version: '3'
services: 
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  
  redis: 
    image: 'redis:latest'
  
  server: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
    # leave node_modules within container as it is, dont map it
      - /app/node_modules
      # map the server dir to app dir, no need to keep building img when src code changed
      - ./server:/app

    # the env variables defined here will get mapped to process.env of nodeJS app
    # where it is used within container
    environment:

    # all values under are default values specified in dockerhub image docs for postgres,redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  

  # worker needs redis connection to fetch indices and push back so specify redis env variables
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app 
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app