name: Deploy multidocker
on:
  push:
    branches:
      - master
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true react-test npm run test
      
      - run: docker build -t multi-client-10-14 ./client
      - run: docker build -t multi-server-10-14 ./server
      - run: docker build -t multi-nginx-10-14 ./nginx
      - run: docker build -t multi-worker-10-14 ./worker
      
      - run: docker push multi-client-10-14
      - run: docker push multi-server-10-14
      - run: docker push multi-worker-10-14
      - run: docker push multi-nginx-10-14
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
        
      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }} 
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-gh
          environment_name: Multi-gh-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-399400614342
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip